import { getAccessToken, setAccessToken, setStoredUser } from './auth-storage';
const API_URL = import.meta.env.VITE_API_URL ?? '/api';
function markApiAvailable(){window.dispatchEvent(new Event('masmax:api-available'))}
function markApiUnavailable(){window.dispatchEvent(new Event('masmax:api-unavailable'))}
function isGatewayUnavailable(status:number){return status===502||status===503||status===504}
function unavailableError(){return new ApiError('No se pudo conectar con la API. Verifica que el backend este disponible.',0)}
export async function probeApi(){try{const response=await fetch(`${API_URL}/health/live`,{credentials:'include',cache:'no-store'});if(response.ok)markApiAvailable();else markApiUnavailable();return response.ok}catch{markApiUnavailable();return false}}
export class ApiError extends Error { constructor(message:string,public readonly status:number,public readonly code?:string,public readonly requestId?:string){super(message)} }
export function getToken(){return getAccessToken()}
let refreshPromise:Promise<boolean>|null=null;
async function refreshAccess(){if(!refreshPromise){refreshPromise=fetch(`${API_URL}/auth/refresh`,{method:'POST',credentials:'include'}).then(async(response)=>{if(isGatewayUnavailable(response.status)){markApiUnavailable();throw unavailableError()}markApiAvailable();if(!response.ok)return false;const body=await response.json() as {accessToken:string;user:import('../types/models').User};setAccessToken(body.accessToken);setStoredUser(body.user);return true}).catch((error:unknown)=>{markApiUnavailable();if(error instanceof ApiError)throw error;throw unavailableError()}).finally(()=>{refreshPromise=null})}return refreshPromise}
export async function restoreSession(){return refreshAccess()}
export async function api<T>(path:string,options:RequestInit={},retry=true):Promise<T>{const token=getToken();let response:Response;try{response=await fetch(`${API_URL}${path}`,{...options,credentials:'include',headers:{...(options.body&&!(options.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...options.headers}})}catch{markApiUnavailable();throw unavailableError()}if(isGatewayUnavailable(response.status)){markApiUnavailable();throw unavailableError()}markApiAvailable();if(response.status===401&&retry&&!path.startsWith('/auth/')){if(await refreshAccess())return api<T>(path,options,false)}if(!response.ok){const body=await response.json().catch(()=>({message:'Error inesperado'})) as {message?:string|string[];code?:string;requestId?:string};const message=Array.isArray(body.message)?body.message.join(', '):body.message;throw new ApiError(message||`La API respondio con estado ${response.status}`,response.status,body.code,body.requestId)}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
export async function apiText(path:string,retry=true):Promise<string>{const token=getToken();let response:Response;try{response=await fetch(`${API_URL}${path}`,{credentials:'include',headers:{...(token?{Authorization:`Bearer ${token}`}:{})}})}catch{throw new ApiError('No se pudo conectar con la API.',0)}if(response.status===401&&retry){if(await refreshAccess())return apiText(path,false)}if(!response.ok){const body=await response.json().catch(()=>({message:'No se pudo cargar el archivo'})) as {message?:string|string[]};throw new ApiError(Array.isArray(body.message)?body.message.join(', '):body.message||'No se pudo cargar el archivo',response.status)}return response.text()}
export async function apiBlob(path:string,retry=true):Promise<Blob>{const token=getToken();let response:Response;try{response=await fetch(`${API_URL}${path}`,{credentials:'include',headers:{...(token?{Authorization:`Bearer ${token}`}:{})}})}catch{throw new ApiError('No se pudo conectar con la API.',0)}if(response.status===401&&retry){if(await refreshAccess())return apiBlob(path,false)}if(!response.ok){const body=await response.json().catch(()=>({message:'No se pudo descargar el archivo'})) as {message?:string|string[]};throw new ApiError(Array.isArray(body.message)?body.message.join(', '):body.message||'No se pudo descargar el archivo',response.status)}return response.blob()}
export const postJson=<T>(path:string,body:unknown)=>api<T>(path,{method:'POST',body:JSON.stringify(body)});
export const putJson=<T>(path:string,body:unknown)=>api<T>(path,{method:'PUT',body:JSON.stringify(body)});
export const putJsonKeepalive=<T>(path:string,body:unknown)=>api<T>(path,{method:'PUT',body:JSON.stringify(body),keepalive:true});
export const patchJson=<T>(path:string,body:unknown)=>api<T>(path,{method:'PATCH',body:JSON.stringify(body)});
export const deleteJson=<T>(path:string)=>api<T>(path,{method:'DELETE'});
export function uploadFile<T>(path:string,file:File,onProgress:(progress:number)=>void):Promise<T>{return new Promise((resolve,reject)=>{const request=new XMLHttpRequest();const data=new FormData();data.append('file',file);request.open('POST',`${API_URL}${path}`);request.withCredentials=true;const token=getToken();if(token)request.setRequestHeader('Authorization',`Bearer ${token}`);request.upload.onprogress=(event)=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))};request.onerror=()=>reject(new ApiError('No se pudo conectar con la API durante la subida.',0));request.onload=()=>{let body:T&{message?:string|string[];requestId?:string};try{body=JSON.parse(request.responseText||'{}') as typeof body}catch{reject(new ApiError('El servidor devolvio una respuesta invalida.',request.status));return}if(request.status>=200&&request.status<300)resolve(body);else{const message=Array.isArray(body.message)?body.message.join(', '):body.message;reject(new ApiError(`${message||'No se pudo subir el archivo.'}${body.requestId?` (ID: ${body.requestId})`:''}`,request.status))}};request.send(data)})}
export function uploadForm<T>(path:string,file:File,fields:Record<string,string|boolean>,onProgress:(progress:number)=>void):Promise<T>{return new Promise((resolve,reject)=>{const request=new XMLHttpRequest();const data=new FormData();data.append('file',file);Object.entries(fields).forEach(([key,value])=>data.append(key,String(value)));request.open('POST',`${API_URL}${path}`);request.withCredentials=true;const token=getToken();if(token)request.setRequestHeader('Authorization',`Bearer ${token}`);request.upload.onprogress=(event)=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))};request.onerror=()=>reject(new ApiError('No se pudo conectar con la API durante la subida.',0));request.onload=()=>{let body:T&{message?:string|string[];requestId?:string};try{body=JSON.parse(request.responseText||'{}') as typeof body}catch{reject(new ApiError('El servidor devolvio una respuesta invalida.',request.status));return}if(request.status>=200&&request.status<300)resolve(body);else{const message=Array.isArray(body.message)?body.message.join(', '):body.message;reject(new ApiError(`${message||'No se pudo subir el subtitulo.'}${body.requestId?` (ID: ${body.requestId})`:''}`,request.status))}};request.send(data)})}
