import { Settings2 } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { toast } from 'sonner';
import { VideoPlayer } from '../../components/VideoPlayer';
import { api, deleteJson, patchJson, postJson } from '../../lib/api';
import { useAsync } from '../../lib/useAsync';
import { Genre, Movie, MovieStatus, VideoSource } from '../../types/models';
import { fieldA11y, FormActions, FormError, FormField, FormLabel, FormSection, NumberInput, Select, TextArea, TextInput } from '../components/AdminForms';
import { AdminTable, Button, FormDisclosure, Panel, ResourceError } from '../components/AdminUi';
import { MultiSelect } from '../components/MultiSelect';
import { validatePlaybackMarkers, videoTypeForSource } from '../components/admin-utils';
import { UploadField } from '../components/UploadField';

const emptyMovie = { title: '', slug: '', description: '', posterUrl: '', bannerUrl: '', videoUrl: '', originalVideoUrl: '', processedVideoUrl: '', videoSource: 'URL' as VideoSource, videoType: 'MP4' as Movie['videoType'], duration: '90', introStartSec: '', introEndSec: '', recapStartSec: '', recapEndSec: '', releaseYear: String(new Date().getFullYear()), genreIds: [] as string[], status: 'DRAFT' as MovieStatus };

export function MoviesAdminPage() {
  const movies = useAsync<Movie[]>(() => api('/admin/movies'), []);
  const genres = useAsync<Genre[]>(() => api('/genres'), []);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState(emptyMovie);
  const [errors, setErrors] = useState<Record<string, string>>({});
  function reset() { setEditingId(null); setForm(emptyMovie); setErrors({}); setFormOpen(false); }
  function edit(item: Movie) { setEditingId(item.id); setFormOpen(true); setErrors({}); setForm({ title: item.title, slug: item.slug, description: item.description, posterUrl: item.posterUrl, bannerUrl: item.bannerUrl, videoUrl: item.videoUrl ?? '', originalVideoUrl: item.originalVideoUrl ?? item.videoUrl ?? '', processedVideoUrl: item.processedVideoUrl ?? item.videoUrl ?? '', videoSource: item.videoSource, videoType: item.videoType, duration: String(item.duration), introStartSec: item.introStartSec == null ? '' : String(item.introStartSec), introEndSec: item.introEndSec == null ? '' : String(item.introEndSec), recapStartSec: item.recapStartSec == null ? '' : String(item.recapStartSec), recapEndSec: item.recapEndSec == null ? '' : String(item.recapEndSec), releaseYear: String(item.releaseYear), genreIds: item.genres.map((genre) => genre.id), status: item.status }); }
  async function submit(event: FormEvent) { event.preventDefault(); const nextErrors = validatePlaybackMarkers({ ...form, durationSec: String(Number(form.duration) * 60) }); if (!form.title.trim()) nextErrors.title = 'El titulo es obligatorio.'; if (!form.posterUrl.trim()) nextErrors.posterUrl = 'La portada es obligatoria.'; if (!form.bannerUrl.trim()) nextErrors.bannerUrl = 'El banner es obligatorio.'; if (!form.videoUrl.trim()) nextErrors.videoUrl = 'Agrega una URL o sube un video.'; if (!form.genreIds.length) nextErrors.genreIds = 'Selecciona al menos un genero.'; if (Number(form.releaseYear) < 1900 || Number(form.releaseYear) > 2200) nextErrors.releaseYear = 'El ano debe ser valido.'; setErrors(nextErrors); if (Object.keys(nextErrors).length) return toast.error('Revisa los campos marcados antes de guardar'); try { const payload = { ...form, duration: Number(form.duration), introStartSec: form.introStartSec ? Number(form.introStartSec) : null, introEndSec: form.introEndSec ? Number(form.introEndSec) : null, recapStartSec: form.recapStartSec ? Number(form.recapStartSec) : null, recapEndSec: form.recapEndSec ? Number(form.recapEndSec) : null, releaseYear: Number(form.releaseYear), originalVideoUrl: form.originalVideoUrl || undefined, processedVideoUrl: form.processedVideoUrl || undefined }; const saved = editingId ? await patchJson<Movie>(`/admin/movies/${editingId}`, payload) : await postJson<Movie>('/admin/movies', payload); movies.setData(editingId ? (movies.data ?? []).map((item) => item.id === saved.id ? saved : item) : [saved, ...(movies.data ?? [])]); toast.success(editingId ? 'Pelicula actualizada' : 'Pelicula creada'); reset(); } catch (error) { toast.error((error as Error).message); } }
  function changeSource(source: VideoSource) { setForm({ ...form, videoSource: source, videoType: videoTypeForSource(source), videoUrl: '', originalVideoUrl: '', processedVideoUrl: '' }); }
  return <Panel title="Peliculas" description="Administra peliculas, material grafico y fuentes de reproduccion." action={<button type="button" className="button-primary" onClick={() => { setEditingId(null); setForm(emptyMovie); setErrors({}); setFormOpen(true); }}>Crear pelicula</button>}>
    <ResourceError message={movies.error ?? genres.error} />
    <FormDisclosure open={formOpen} title="Pelicula" description="Los campos avanzados permanecen ocultos hasta que los necesites." editing={Boolean(editingId)} onToggle={() => setFormOpen((value) => !value)}><form onSubmit={submit} className="grid gap-5">
      <FormSection title="Informacion basica">
        <FormField><FormLabel htmlFor="movie-title" required>Titulo</FormLabel><TextInput id="movie-title" value={form.title} {...fieldA11y('movie-title', undefined, errors.title)} onChange={(event) => setForm({ ...form, title: event.target.value })} /><FormError id="movie-title-error">{errors.title}</FormError></FormField>
        <FormField><FormLabel htmlFor="movie-slug">Slug</FormLabel><TextInput id="movie-slug" placeholder="titulo-de-la-pelicula" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /></FormField>
        <FormField><FormLabel htmlFor="movie-year" required>Ano de estreno</FormLabel><NumberInput id="movie-year" min={1900} max={2200} value={form.releaseYear} {...fieldA11y('movie-year', undefined, errors.releaseYear)} onChange={(event) => setForm({ ...form, releaseYear: event.target.value })} /><FormError id="movie-year-error">{errors.releaseYear}</FormError></FormField>
        <FormField><FormLabel htmlFor="movie-status" required>Estado</FormLabel><Select id="movie-status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as MovieStatus })}><option value="DRAFT">Borrador</option><option value="PUBLISHED">Publicada</option><option value="HIDDEN">Oculta</option></Select></FormField>
        <FormField><FormLabel htmlFor="movie-duration" required>Duracion en minutos</FormLabel><NumberInput id="movie-duration" min={1} value={form.duration} onChange={(event) => setForm({ ...form, duration: event.target.value })} /></FormField>
        <FormField fullWidth><FormLabel htmlFor="movie-description" required>Descripcion</FormLabel><TextArea id="movie-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></FormField>
      </FormSection>
      <FormSection title="Imagenes">
        <FormField><FormLabel htmlFor="movie-poster" required>Portada URL</FormLabel><TextInput id="movie-poster" type="url" placeholder="https://..." value={form.posterUrl} {...fieldA11y('movie-poster', undefined, errors.posterUrl)} onChange={(event) => setForm({ ...form, posterUrl: event.target.value })} /><FormError id="movie-poster-error">{errors.posterUrl}</FormError></FormField><UploadField type="image" label="Subir portada" onUploaded={(posterUrl) => setForm({ ...form, posterUrl })} />
        <FormField><FormLabel htmlFor="movie-banner" required>Banner URL</FormLabel><TextInput id="movie-banner" type="url" placeholder="https://..." value={form.bannerUrl} {...fieldA11y('movie-banner', undefined, errors.bannerUrl)} onChange={(event) => setForm({ ...form, bannerUrl: event.target.value })} /><FormError id="movie-banner-error">{errors.bannerUrl}</FormError></FormField><UploadField type="image" label="Subir banner" onUploaded={(bannerUrl) => setForm({ ...form, bannerUrl })} />
      </FormSection>
      <FormSection title="Fuente de video">
        <FormField><FormLabel htmlFor="movie-source" required>Fuente</FormLabel><Select id="movie-source" value={form.videoSource} onChange={(event) => changeSource(event.target.value as VideoSource)}><option value="LOCAL">Subir video local MP4</option><option value="URL">URL externa MP4</option><option value="HLS">URL HLS .m3u8</option><option value="DRIVE">URL de Google Drive</option><option value="EMBED">Embed iframe</option></Select></FormField>
        {form.videoSource !== 'LOCAL' ? <FormField><FormLabel htmlFor="movie-video-url" required>URL del video</FormLabel><TextInput id="movie-video-url" type="url" placeholder="https://..." value={form.originalVideoUrl} {...fieldA11y('movie-video-url', undefined, errors.videoUrl)} onChange={(event) => setForm({ ...form, originalVideoUrl: event.target.value, videoUrl: event.target.value, processedVideoUrl: '' })} /><FormError id="movie-video-url-error">{errors.videoUrl}</FormError></FormField> : <FormField><UploadField type="video" label="Subir pelicula MP4 local 1080p" onUploaded={(url, mimeType, details) => setForm({ ...form, videoUrl: url, originalVideoUrl: details?.originalUrl ?? url, processedVideoUrl: url, posterUrl: form.posterUrl || details?.thumbnailUrl || '', videoSource: 'LOCAL', videoType: mimeType.includes('mpegurl') ? 'HLS' : 'MP4' })} /><FormError>{errors.videoUrl}</FormError></FormField>}
        {form.videoUrl && <div className="md:col-span-2"><VideoPlayer src={form.processedVideoUrl || form.videoUrl} originalSrc={form.originalVideoUrl} source={form.videoSource} type={form.videoType} poster={form.posterUrl || undefined} /></div>}
      </FormSection>
      <FormSection title="Clasificacion"><FormField fullWidth><MultiSelect id="movie-genres" label="Generos" options={(genres.data ?? []).map((genre) => ({ value: genre.id, label: genre.name }))} value={form.genreIds} onChange={(genreIds) => setForm({ ...form, genreIds })} error={errors.genreIds} /></FormField></FormSection>
      <details className="group rounded-2xl border border-line bg-ink/25"><summary className="flex min-h-14 cursor-pointer list-none items-center gap-3 px-4 font-semibold text-white sm:px-5"><Settings2 size={18} className="text-brand" />Reproduccion avanzada<span className="ml-auto text-xs font-normal text-slate-400 group-open:hidden">Mostrar</span></summary><div className="grid gap-4 border-t border-line p-4 md:grid-cols-2 sm:p-5">{([['introStartSec', 'Inicio de introduccion'], ['introEndSec', 'Fin de introduccion'], ['recapStartSec', 'Inicio de resumen'], ['recapEndSec', 'Fin de resumen']] as const).map(([key, label]) => <FormField key={key}><FormLabel htmlFor={`movie-${key}`}>{label} (segundos)</FormLabel><NumberInput id={`movie-${key}`} min={0} value={form[key]} {...fieldA11y(`movie-${key}`, undefined, errors[key])} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /><FormError id={`movie-${key}-error`}>{errors[key]}</FormError></FormField>)}</div></details>
      <FormActions><button type="button" className="button-secondary" onClick={reset}>Cancelar</button><Button>{editingId ? 'Guardar cambios' : 'Crear pelicula'}</Button></FormActions>
    </form></FormDisclosure>
    <AdminTable rows={movies.data ?? []} columns={[{ key: 'poster', label: 'Portada', render: (movie) => <img src={movie.posterUrl} alt="" className="h-12 w-9 rounded object-cover" /> }, 'title', 'releaseYear', 'duration', 'status', 'videoType']} onEdit={edit} onDelete={async (id) => { await deleteJson(`/admin/movies/${id}`); movies.setData((movies.data ?? []).filter((item) => item.id !== id)); }} rowLabel={(movie) => movie.title} deleteTitle="Eliminar pelicula" deleteDescription="La pelicula dejara de estar disponible en el catalogo." emptyMessage="No hay peliculas registradas" emptyDescription="Crea la primera pelicula para ampliar el catalogo." />
  </Panel>;
}
