import Hls from 'hls.js';
import { useEffect, useMemo, useRef, useState } from 'react';
import { api, putJson } from '../lib/api';
import { VideoSource, VideoType, WatchHistory } from '../types/models';
const playbackError='No se pudo reproducir el video. Verifica que el enlace sea publico o que el formato sea compatible.';
function driveFileId(value:string){try{const url=new URL(value);return url.pathname.match(/\/file\/d\/([a-zA-Z0-9_-]+)/)?.[1]??url.searchParams.get('id')}catch{return null}}
export function VideoPlayer({src,type,source,originalSrc,poster,episodeId,movieId}:{src:string;type:VideoType;source?:VideoSource;originalSrc?:string;poster?:string;episodeId?:string;movieId?:string}){const videoRef=useRef<HTMLVideoElement|null>(null);const[error,setError]=useState<string|null>(null);const[driveFallback,setDriveFallback]=useState(false);const[playbackSrc,setPlaybackSrc]=useState(src);const isDrive=type==='DRIVE'||source==='DRIVE';const previewUrl=useMemo(()=>{const id=driveFileId(originalSrc||src);return id?`https://drive.google.com/file/d/${encodeURIComponent(id)}/preview`:null},[originalSrc,src]);
useEffect(()=>{setDriveFallback(false);setError(null);setPlaybackSrc(src);if(source==='LOCAL'&&(episodeId||movieId)){const params=new URLSearchParams(episodeId?{episodeId}:{movieId:movieId!});api<{url:string}>(`/media/authorize?${params}`).then((result)=>setPlaybackSrc(result.url)).catch((reason:Error)=>setError(reason.message))}},[src,source,episodeId,movieId]);
useEffect(()=>{if(type==='EMBED'||(isDrive&&driveFallback))return;const video=videoRef.current;if(!video)return;setError(null);let hls:Hls|undefined;if(type==='HLS'&&Hls.isSupported()){hls=new Hls();hls.loadSource(playbackSrc);hls.attachMedia(video);hls.on(Hls.Events.ERROR,(_event,data)=>{if(data.fatal)setError(playbackError)})}else if(type==='HLS'&&video.canPlayType('application/vnd.apple.mpegurl'))video.src=playbackSrc;else if(type==='HLS')setError(playbackError);else video.src=playbackSrc;return()=>hls?.destroy()},[driveFallback,isDrive,playbackSrc,type]);
useEffect(()=>{const video=videoRef.current;if(!video||(!episodeId&&!movieId))return;let restored=false;api<WatchHistory[]>('/me/watch-history?limit=100').then((items)=>{const item=items.find((entry)=>entry.episodeId===episodeId||entry.movieId===movieId);if(item&&item.positionSec>0&&!item.completedAt){video.currentTime=item.positionSec;restored=true}}).catch(()=>undefined);const save=(completed=false)=>{if(!Number.isFinite(video.duration)||video.duration<=0)return;void putJson('/me/progress',{episodeId,movieId,positionSec:Math.floor(video.currentTime),durationSec:Math.floor(video.duration),completed}).catch(()=>undefined)};const interval=window.setInterval(()=>save(false),15_000);const onPause=()=>save(false);const onEnded=()=>save(true);video.addEventListener('pause',onPause);video.addEventListener('ended',onEnded);return()=>{window.clearInterval(interval);video.removeEventListener('pause',onPause);video.removeEventListener('ended',onEnded);if(restored||video.currentTime>0)save(false)}},[episodeId,movieId,playbackSrc]);
if(type==='EMBED'||(isDrive&&driveFallback)){const iframeSrc=isDrive?previewUrl:playbackSrc;if(!iframeSrc)return <VideoError message={playbackError}/>;try{const parsed=new URL(iframeSrc);const allowed=String(import.meta.env.VITE_ALLOWED_EMBED_DOMAINS??'youtube.com,player.vimeo.com,drive.google.com').split(',').map((d)=>d.trim().toLowerCase()).filter(Boolean);const host=parsed.hostname.toLowerCase();if(parsed.protocol!=='https:'||!allowed.some((d)=>host===d||host.endsWith(`.${d}`)))return <VideoError message="El enlace embed no esta permitido."/>}catch{return <VideoError message={playbackError}/>}return <div><iframe src={iframeSrc} title="Reproductor de video" className="aspect-video w-full rounded-lg border border-line bg-black" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>{isDrive&&<p className="mt-3 text-sm text-slate-400">Google Drive debe estar compartido como cualquier persona con el enlace. Drive puede limitar la reproduccion.</p>}</div>}
return <div><video ref={videoRef} className="aspect-video w-full rounded-lg border border-line bg-black" controls playsInline preload="metadata" poster={poster} onError={()=>{if(isDrive&&previewUrl)setDriveFallback(true);else setError(playbackError)}}/>{error&&<VideoError message={error}/>}</div>}
function VideoError({message}:{message:string}){return <p className="mt-3 rounded-lg border border-coral/40 bg-coral/10 p-3 text-sm text-coral">{message}</p>}
