export { AuditAdminPage } from './audit/AuditAdminPage';
export { CommentsAdminPage } from './comments/CommentsAdminPage';
export { DashboardPage } from './dashboard/DashboardPage';
export { EpisodesAdminPage } from './episodes/EpisodesAdminPage';
export { GenresAdminPage } from './genres/GenresAdminPage';
export { MoviesAdminPage } from './movies/MoviesAdminPage';
export { SeriesAdminPage } from './series/SeriesAdminPage';
export { SeasonsAdminPage } from './seasons/SeasonsAdminPage';
export { DesignAdminPage, SettingsAdminPage } from './settings/SettingsAdminPage';
export { StorageAdminPage } from './storage/StorageAdminPage';
export { SubtitlesAdminPage } from './subtitles/SubtitlesAdminPage';
export { UsersAdminPage } from './users/UsersAdminPage';
export { VideoProcessingAdminPage } from './processing/VideoProcessingAdminPage';
