import { FormEvent, useState } from 'react';
import { toast } from 'sonner';
import { LoadingBlock } from '../../components/Layout';
import { api, patchJson } from '../../lib/api';
import { useAsync } from '../../lib/useAsync';
import { Series, SiteSetting } from '../../types/models';
import { Checkbox, FormActions, FormField, FormHint, FormLabel, FormSection, Select, TextArea, TextInput } from '../components/AdminForms';
import { Button, Panel, ResourceError } from '../components/AdminUi';
import { UploadField } from '../components/UploadField';

export function SettingsAdminPage() {
  const settings = useAsync<SiteSetting>(() => api('/settings'), []);
  const [form, setForm] = useState<Partial<SiteSetting>>({});
  const current: Partial<SiteSetting> = { ...(settings.data ?? {}), ...form };
  async function submit(event: FormEvent) { event.preventDefault(); try { const { siteName, logo, primaryColor, facebook, instagram, youtube, tiktok } = current; const updated = await patchJson<SiteSetting>('/admin/settings', { siteName, logo, primaryColor, facebook, instagram, youtube, tiktok }); settings.setData(updated); setForm({}); toast.success('Configuracion guardada'); } catch (error) { toast.error((error as Error).message); } }
  return <Panel title="Configuracion" description="Actualiza la identidad principal y los enlaces sociales del sitio."><ResourceError message={settings.error} />{settings.loading ? <LoadingBlock /> : <form onSubmit={submit} className="grid gap-5">
    <FormSection title="Identidad"><FormField><FormLabel htmlFor="settings-name">Nombre del sitio</FormLabel><TextInput id="settings-name" value={current.siteName ?? ''} onChange={(event) => setForm({ ...form, siteName: event.target.value })} /></FormField><FormField><FormLabel htmlFor="settings-logo">Logo URL</FormLabel><TextInput id="settings-logo" type="url" placeholder="https://..." value={current.logo ?? ''} onChange={(event) => setForm({ ...form, logo: event.target.value })} /></FormField><FormField><FormLabel htmlFor="settings-primary">Color principal</FormLabel><TextInput id="settings-primary" type="color" value={current.primaryColor ?? '#22d3ee'} onChange={(event) => setForm({ ...form, primaryColor: event.target.value })} /></FormField></FormSection>
    <FormSection title="Redes sociales" description="Deja vacio cualquier perfil que no quieras mostrar.">{([['facebook', 'Facebook'], ['instagram', 'Instagram'], ['youtube', 'YouTube'], ['tiktok', 'TikTok']] as const).map(([key, label]) => <FormField key={key}><FormLabel htmlFor={`settings-${key}`}>{label}</FormLabel><TextInput id={`settings-${key}`} type="url" placeholder="https://..." value={current[key] ?? ''} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></FormField>)}</FormSection>
    <FormActions><Button>Guardar configuracion</Button></FormActions>
  </form>}</Panel>;
}

export function DesignAdminPage() {
  const settings = useAsync<SiteSetting>(() => api('/site-settings'), []);
  const series = useAsync<Series[]>(() => api('/admin/series'), []);
  const [form, setForm] = useState<Partial<SiteSetting>>({});
  const current = { ...(settings.data ?? {}), ...form } as Partial<SiteSetting>;
  async function submit(event: FormEvent) { event.preventDefault(); try { const { siteName, logo, favicon, primaryColor, secondaryColor, colorMode, heroTitle, heroText, heroImage, featuredSeriesIds, sectionOrder, showLatestEpisodes, showPopularSeries, showGenres, showComments, showFooter, footerText, facebook, instagram, youtube, tiktok } = current; const updated = await patchJson<SiteSetting>('/admin/site-settings', { siteName, logo, favicon, primaryColor, secondaryColor, colorMode, heroTitle, heroText, heroImage, featuredSeriesIds, sectionOrder, showLatestEpisodes, showPopularSeries, showGenres, showComments, showFooter, footerText, facebook, instagram, youtube, tiktok }); settings.setData(updated); setForm({}); toast.success('Diseno guardado. Recarga el sitio publico para verlo.'); } catch (error) { toast.error((error as Error).message); } }
  function toggleFeatured(id: string) { const ids = current.featuredSeriesIds ?? []; setForm({ ...form, featuredSeriesIds: ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id] }); }
  return <Panel title="Diseno del sitio" description="Personaliza colores, imagenes y secciones visibles sin cambiar el contenido."><ResourceError message={settings.error ?? series.error} />{settings.loading ? <LoadingBlock /> : <form onSubmit={submit} className="grid gap-5">
    <FormSection title="Identidad visual">
      <FormField><FormLabel htmlFor="design-name">Nombre del sitio</FormLabel><TextInput id="design-name" value={current.siteName ?? ''} onChange={(event) => setForm({ ...form, siteName: event.target.value })} /></FormField>
      <FormField><FormLabel htmlFor="design-mode">Modo de color</FormLabel><Select id="design-mode" value={current.colorMode ?? 'dark'} onChange={(event) => setForm({ ...form, colorMode: event.target.value as SiteSetting['colorMode'] })}><option value="dark">Modo oscuro</option><option value="light">Modo claro</option></Select></FormField>
      <FormField><FormLabel htmlFor="design-logo">Logo URL</FormLabel><TextInput id="design-logo" type="url" placeholder="https://..." value={current.logo ?? ''} onChange={(event) => setForm({ ...form, logo: event.target.value })} /></FormField><UploadField type="image" label="Subir logo" onUploaded={(url) => setForm({ ...form, logo: url })} />
      <FormField><FormLabel htmlFor="design-favicon">Favicon URL</FormLabel><TextInput id="design-favicon" type="url" placeholder="https://..." value={current.favicon ?? ''} onChange={(event) => setForm({ ...form, favicon: event.target.value })} /></FormField><UploadField type="image" label="Subir favicon" onUploaded={(url) => setForm({ ...form, favicon: url })} />
      <FormField><FormLabel htmlFor="design-primary">Color principal</FormLabel><TextInput id="design-primary" type="color" value={current.primaryColor ?? '#22d3ee'} onChange={(event) => setForm({ ...form, primaryColor: event.target.value })} /></FormField><FormField><FormLabel htmlFor="design-secondary">Color secundario</FormLabel><TextInput id="design-secondary" type="color" value={current.secondaryColor ?? '#fb7185'} onChange={(event) => setForm({ ...form, secondaryColor: event.target.value })} /></FormField>
    </FormSection>
    <FormSection title="Hero principal"><FormField><FormLabel htmlFor="design-hero-title">Titulo del hero</FormLabel><TextInput id="design-hero-title" value={current.heroTitle ?? ''} onChange={(event) => setForm({ ...form, heroTitle: event.target.value })} /></FormField><FormField><FormLabel htmlFor="design-hero-image">Imagen del hero URL</FormLabel><TextInput id="design-hero-image" type="url" placeholder="https://..." value={current.heroImage ?? ''} onChange={(event) => setForm({ ...form, heroImage: event.target.value })} /></FormField><FormField fullWidth><FormLabel htmlFor="design-hero-text">Texto del hero</FormLabel><TextArea id="design-hero-text" value={current.heroText ?? ''} onChange={(event) => setForm({ ...form, heroText: event.target.value })} /></FormField><FormField fullWidth><UploadField type="image" label="Subir banner del hero" onUploaded={(url) => setForm({ ...form, heroImage: url })} /></FormField></FormSection>
    <FormSection title="Contenido destacado"><FormField fullWidth><p className="mb-2 text-sm font-medium text-slate-200">Series destacadas</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(series.data ?? []).map((item) => <Checkbox key={item.id} label={item.title} checked={(current.featuredSeriesIds ?? []).includes(item.id)} onChange={() => toggleFeatured(item.id)} />)}</div></FormField><FormField fullWidth><FormLabel htmlFor="design-order">Orden de secciones</FormLabel><TextInput id="design-order" value={(current.sectionOrder ?? []).join(',')} onChange={(event) => setForm({ ...form, sectionOrder: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /><FormHint>Escribe las claves separadas por comas. Se conserva el formato esperado por el sitio.</FormHint></FormField></FormSection>
    <FormSection title="Visibilidad de secciones">{([['showLatestEpisodes', 'Mostrar ultimos episodios'], ['showPopularSeries', 'Mostrar series populares'], ['showGenres', 'Mostrar generos'], ['showComments', 'Mostrar comentarios'], ['showFooter', 'Mostrar footer']] as const).map(([key, label]) => <Checkbox key={key} label={label} checked={current[key] ?? true} onChange={(event) => setForm({ ...form, [key]: event.target.checked })} />)}<FormField fullWidth><FormLabel htmlFor="design-footer">Texto del footer</FormLabel><TextInput id="design-footer" value={current.footerText ?? ''} onChange={(event) => setForm({ ...form, footerText: event.target.value })} /></FormField></FormSection>
    <FormActions><Button>Guardar diseno</Button></FormActions>
  </form>}</Panel>;
}
