import { memo, useState } from 'react';
import { toast } from 'sonner';
import { patchJson, postJson } from '../../lib/api';
import { Episode, VideoSource } from '../../types/models';
import { FormField, FormLabel, Select, TextInput } from '../components/AdminForms';
import { Button } from '../components/AdminUi';
import { videoTypeForSource } from '../components/admin-utils';

type Draft = { title: string; videoUrl: string };
export const BulkEpisodeTools = memo(function BulkEpisodeTools({ seriesId, seasonId, episodes, selected, onSelected, onChanged }: { seriesId: string; seasonId: string; episodes: Episode[]; selected: string[]; onSelected: (ids: string[]) => void; onChanged: () => void }) {
  const [drafts, setDrafts] = useState<Draft[]>([{ title: '', videoUrl: '' }]);
  const [source, setSource] = useState<VideoSource>('URL');
  const [copySource, setCopySource] = useState('');
  const [busy, setBusy] = useState(false);
  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); try { await action(); toast.success(message); onChanged(); } catch (error) { toast.error((error as Error).message); } finally { setBusy(false); } }
  async function createBulk() { const valid = drafts.filter((draft) => draft.title.trim() && draft.videoUrl.trim()); if (!seriesId || !seasonId) return toast.error('Selecciona serie y temporada'); if (!valid.length) return toast.error('Completa al menos un episodio'); await run(() => postJson('/admin/episodes/bulk', { seriesId, seasonId, episodes: valid.map((draft) => ({ ...draft, videoSource: source, videoType: videoTypeForSource(source), published: false })) }), 'Episodios creados como borrador'); setDrafts([{ title: '', videoUrl: '' }]); }
  function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= episodes.length) return; const current = episodes[index]; const destination = episodes[target]; void run(() => patchJson('/admin/episodes/reorder', { seasonId, items: [{ id: current.id, position: destination.position }, { id: destination.id, position: current.position }] }), 'Orden actualizado'); }
  return <section className="mb-6 grid gap-4 xl:grid-cols-2">
    <div className="rounded-xl border border-line bg-ink/40 p-4"><h2 className="mb-3 text-lg font-semibold text-white">Creacion masiva</h2><FormField><FormLabel htmlFor="bulk-source">Fuente del lote</FormLabel><Select id="bulk-source" value={source} onChange={(event) => setSource(event.target.value as VideoSource)}><option value="URL">MP4 externa</option><option value="HLS">HLS</option><option value="DRIVE">Google Drive</option><option value="EMBED">Embed</option></Select></FormField><div className="my-3 grid gap-3">{drafts.map((draft, index) => <div key={index} className="grid gap-3 rounded-xl border border-line p-3 sm:grid-cols-2"><FormField><FormLabel htmlFor={`bulk-title-${index}`}>Titulo del episodio {index + 1}</FormLabel><TextInput id={`bulk-title-${index}`} value={draft.title} onChange={(event) => setDrafts(drafts.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} /></FormField><FormField><FormLabel htmlFor={`bulk-url-${index}`}>URL del video</FormLabel><TextInput id={`bulk-url-${index}`} type="url" placeholder="https://..." value={draft.videoUrl} onChange={(event) => setDrafts(drafts.map((item, itemIndex) => itemIndex === index ? { ...item, videoUrl: event.target.value } : item))} /></FormField></div>)}</div><div className="flex flex-wrap gap-2"><button type="button" className="button-secondary" onClick={() => setDrafts([...drafts, { title: '', videoUrl: '' }])}>Agregar fila</button><Button type="button" disabled={busy} onClick={() => void createBulk()}>Crear lote</Button></div></div>
    <div className="rounded-xl border border-line bg-ink/40 p-4"><h2 className="mb-3 text-lg font-semibold text-white">Acciones sobre seleccionados</h2><p className="mb-3 text-sm text-slate-400">{selected.length} episodios seleccionados</p><div className="mb-4 flex flex-wrap gap-2"><Button type="button" disabled={busy || !selected.length} onClick={() => void run(() => patchJson('/admin/episodes/publish', { ids: selected, published: true }), 'Episodios publicados')}>Publicar</Button><button type="button" disabled={busy || !selected.length} className="button-secondary disabled:opacity-50" onClick={() => void run(() => patchJson('/admin/episodes/publish', { ids: selected, published: false }), 'Episodios ocultados')}>Despublicar</button></div><FormField><FormLabel htmlFor="copy-source">Episodio de origen</FormLabel><Select id="copy-source" value={copySource} onChange={(event) => setCopySource(event.target.value)}><option value="">Selecciona un episodio</option>{episodes.map((episode) => <option key={episode.id} value={episode.id}>T{episode.season?.number} E{episode.number} · {episode.title}</option>)}</Select></FormField><Button type="button" className="mt-2" disabled={busy || !copySource || !selected.filter((id) => id !== copySource).length} onClick={() => void run(() => postJson('/admin/episodes/copy-settings', { sourceEpisodeId: copySource, targetEpisodeIds: selected.filter((id) => id !== copySource), fields: ['video', 'thumbnail', 'duration'] }), 'Configuracion copiada')}>Copiar a seleccionados</Button><div className="mt-4 border-t border-line pt-3"><p className="mb-2 text-sm font-semibold">Orden rapido</p>{episodes.map((episode, index) => <div key={episode.id} className="flex items-center justify-between border-b border-line/50 py-1 text-sm"><span>{episode.number}. {episode.title}</span><span><button type="button" aria-label={`Subir ${episode.title}`} disabled={busy || index === 0} className="min-h-9 px-2" onClick={() => move(index, -1)}>↑</button><button type="button" aria-label={`Bajar ${episode.title}`} disabled={busy || index === episodes.length - 1} className="min-h-9 px-2" onClick={() => move(index, 1)}>↓</button></span></div>)}</div>{selected.length > 0 && <button type="button" className="mt-3 text-sm text-slate-400 underline" onClick={() => onSelected([])}>Limpiar seleccion</button>}</div>
  </section>;
});
