import { useState } from 'react';
import { toast } from 'sonner';
import { postJson } from '../../lib/api';
import { FormField, FormHint, FormLabel, TextArea } from '../components/AdminForms';
import { Button, ResourceError } from '../components/AdminUi';
import { FileSelectionField } from '../components/UploadField';
type PreviewRow = { row: number; season: number | null; episode: number | null; title: string; valid: boolean; errors: string[] };
type Preview = { rows: PreviewRow[]; validCount: number; errorCount: number };
const sample = 'season,episode,title,videoUrl,videoSource,videoType,duration,published,publishedAt\n1,1,Episodio piloto,https://example.com/demo.mp4,URL,MP4,1440,false,2026-01-01';
export function CsvEpisodeImport({ seriesId, onImported }: { seriesId: string; onImported: () => void }) {
  const [csv, setCsv] = useState(''); const [csvFile, setCsvFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function readFile(file: File | null) { setCsvFile(file); if (file) { setCsv(await file.text()); setPreview(null); } }
  async function runPreview() { if (!seriesId) return toast.error('Selecciona una serie'); if (!csv.trim()) return toast.error('Carga o pega un CSV'); setBusy(true); setError(null); try { setPreview(await postJson<Preview>('/admin/episodes/import/preview', { seriesId, csv })); } catch (caught) { setError((caught as Error).message); } finally { setBusy(false); } }
  async function commit() { setBusy(true); try { const result = await postJson<{ imported: number }>('/admin/episodes/import/commit', { seriesId, csv }); toast.success(`${result.imported} episodios importados`); setCsv(''); setCsvFile(null); setPreview(null); onImported(); } catch (caught) { setError((caught as Error).message); } finally { setBusy(false); } }
  return <section className="mt-6 rounded-xl border border-line bg-ink/40 p-4"><h2 className="mb-1 text-lg font-semibold text-white">Importar CSV</h2><p className="mb-4 text-sm text-slate-400">Columnas obligatorias: season, episode, title y videoUrl. Maximo 500 filas.</p><FileSelectionField id="csv-import-file" label="Archivo CSV" accept=".csv,text/csv" hint="CSV con un maximo de 500 filas." file={csvFile} disabled={busy} onChange={(file) => void readFile(file)} /><FormField className="mt-4"><FormLabel htmlFor="csv-content">Contenido CSV</FormLabel><TextArea id="csv-content" value={csv} placeholder={sample} onChange={(event) => { setCsv(event.target.value); setPreview(null); }} /><FormHint>Puedes revisar o pegar manualmente el contenido antes de validarlo.</FormHint></FormField><ResourceError message={error} /><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Button type="button" disabled={busy || !seriesId} onClick={() => void runPreview()}>{busy ? 'Validando...' : 'Validar vista previa'}</Button>{preview && preview.errorCount === 0 && <Button type="button" disabled={busy} onClick={() => void commit()}>Importar {preview.validCount}</Button>}</div>{preview && <div className="admin-table-shell mt-4"><p className="p-3 text-sm font-semibold text-slate-200">Validos: {preview.validCount} · Con errores: {preview.errorCount}</p><table><thead><tr><th>Fila</th><th>Temporada</th><th>Episodio</th><th>Titulo</th><th>Resultado</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.row}><td>{row.row}</td><td>{row.season ?? '-'}</td><td>{row.episode ?? '-'}</td><td>{row.title}</td><td className={row.valid ? 'text-mint' : 'text-coral'}>{row.valid ? 'Valido' : row.errors.join('; ')}</td></tr>)}</tbody></table></div>}</section>;
}
