import { FormEvent, useState } from 'react';
import { toast } from 'sonner';
import { api, deleteJson, patchJson, postJson } from '../../lib/api';
import { useAsync } from '../../lib/useAsync';
import { Role, User } from '../../types/models';
import { Checkbox, fieldA11y, FormActions, FormError, FormField, FormHint, FormLabel, FormSection, Select, TextInput } from '../components/AdminForms';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { AdminTable, Button, FormDisclosure, Panel, ResourceError } from '../components/AdminUi';

const emptyUser = { name: '', email: '', role: 'USER' as Role, active: true, password: '', confirmPassword: '' };
export function UsersAdminPage() {
  const users = useAsync<User[]>(() => api('/admin/users'), []);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState(emptyUser);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [pendingRevoke, setPendingRevoke] = useState<User | null>(null);
  function reset() { setEditingId(null); setForm(emptyUser); setErrors({}); setFormOpen(false); }
  function edit(user: User) { setEditingId(user.id ?? null); setFormOpen(true); setErrors({}); setForm({ name: user.name, email: user.email, role: user.role, active: user.active ?? true, password: '', confirmPassword: '' }); }
  function validatePassword(required: boolean) { const next: Record<string, string> = {}; if (required && form.password.length < 8) next.password = 'La contrasena debe tener al menos 8 caracteres.'; if (form.password && form.password.length < 8) next.password = 'La contrasena debe tener al menos 8 caracteres.'; if ((required || form.password) && form.password !== form.confirmPassword) next.confirmPassword = 'Las contrasenas no coinciden.'; return next; }
  async function submit(event: FormEvent) { event.preventDefault(); const nextErrors = validatePassword(!editingId); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; try { const saved = editingId ? await patchJson<User>(`/admin/users/${editingId}`, { name: form.name, email: form.email, role: form.role, active: form.active }) : await postJson<User>('/admin/users', { name: form.name, email: form.email, role: form.role, active: form.active, password: form.password }); users.setData(editingId ? (users.data ?? []).map((item) => item.id === saved.id ? saved : item) : [saved, ...(users.data ?? [])]); toast.success(editingId ? 'Usuario actualizado' : 'Usuario creado'); reset(); } catch (error) { toast.error((error as Error).message); } }
  async function changePassword() { if (!editingId) return; const nextErrors = validatePassword(true); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; try { await patchJson(`/admin/users/${editingId}/password`, { password: form.password, confirmPassword: form.confirmPassword }); setForm({ ...form, password: '', confirmPassword: '' }); toast.success('Contrasena actualizada'); } catch (error) { toast.error((error as Error).message); } }
  async function revoke() { if (!pendingRevoke?.id) return; try { const result = await deleteJson<{ revoked: number }>(`/admin/users/${pendingRevoke.id}/sessions`); toast.success(`${result.revoked} sesiones revocadas`); setPendingRevoke(null); } catch (error) { toast.error((error as Error).message); } }
  return <Panel title="Usuarios" description="Gestiona identidad, permisos, estado y credenciales de acceso." action={<button type="button" className="button-primary" onClick={() => { setEditingId(null); setForm(emptyUser); setErrors({}); setFormOpen(true); }}>Crear usuario</button>}>
    <ResourceError message={users.error} />
    <FormDisclosure open={formOpen} title="Usuario" description="La contrasena nunca se muestra ni se recupera desde el servidor." editing={Boolean(editingId)} onToggle={() => setFormOpen((value) => !value)}><form onSubmit={submit} className="grid gap-5">
      <FormSection title="Datos de la cuenta"><FormField><FormLabel htmlFor="user-name" required>Nombre</FormLabel><TextInput id="user-name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></FormField><FormField><FormLabel htmlFor="user-email" required>Email</FormLabel><TextInput id="user-email" required type="email" autoComplete="off" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></FormField><FormField><FormLabel htmlFor="user-role" required>Rol</FormLabel><Select id="user-role" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as Role })}><option value="USER">Usuario</option><option value="ADMIN">Administrador</option></Select></FormField><FormField><Checkbox label="Usuario activo" hint="Los usuarios inactivos no pueden iniciar sesion." checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /></FormField></FormSection>
      <FormSection title={editingId ? 'Cambiar contrasena' : 'Credenciales'} description={editingId ? 'Completa ambos campos solo cuando quieras cambiar la contrasena.' : 'La contrasena debe tener al menos 8 caracteres.'}><FormField><FormLabel htmlFor="user-password" required={!editingId}>{editingId ? 'Nueva contrasena' : 'Contrasena'}</FormLabel><TextInput id="user-password" type="password" minLength={8} autoComplete="new-password" value={form.password} {...fieldA11y('user-password', 'hint', errors.password)} onChange={(event) => setForm({ ...form, password: event.target.value })} /><FormHint id="user-password-hint">Minimo 8 caracteres.</FormHint><FormError id="user-password-error">{errors.password}</FormError></FormField><FormField><FormLabel htmlFor="user-confirm-password" required={!editingId}>Confirmar contrasena</FormLabel><TextInput id="user-confirm-password" type="password" minLength={8} autoComplete="new-password" value={form.confirmPassword} {...fieldA11y('user-confirm-password', undefined, errors.confirmPassword)} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} /><FormError id="user-confirm-password-error">{errors.confirmPassword}</FormError></FormField>{editingId && form.password && <FormField fullWidth><button type="button" className="button-secondary" onClick={() => void changePassword()}>Cambiar contrasena</button></FormField>}</FormSection>
      <FormActions><button type="button" className="button-secondary" onClick={reset}>Cancelar</button><Button>{editingId ? 'Guardar usuario' : 'Crear usuario'}</Button></FormActions>
    </form></FormDisclosure>
    <AdminTable rows={users.data ?? []} columns={['name', 'email', 'role', 'active']} onEdit={edit} onDelete={async (id) => { await deleteJson(`/admin/users/${id}`); users.setData((users.data ?? []).filter((item) => item.id !== id)); }} rowLabel={(user) => user.name || user.email} deleteTitle="Eliminar usuario" deleteDescription="La cuenta perdera el acceso y se eliminaran sus datos asociados segun las reglas del servidor." extraAction={(row) => <button type="button" className="rounded-lg border border-warning px-3 py-1.5 text-warning" onClick={() => setPendingRevoke(row)}>Revocar sesiones</button>} emptyMessage="No hay usuarios registrados" />
    <ConfirmDialog open={Boolean(pendingRevoke)} title="Revocar sesiones" itemName={pendingRevoke?.email} description="Se cerraran todas las sesiones activas de este usuario. Podra volver a iniciar sesion si la cuenta sigue activa." confirmLabel="Revocar sesiones" onCancel={() => setPendingRevoke(null)} onConfirm={() => void revoke()} />
  </Panel>;
}
